services:
  - type: web
    runtime: docker
    name: fastapi-EHR
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
    dockerfilePath: "EHR/app/backend/Dockerfile"

  - type: web
    name: streamlit-EHR
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8501"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: BACKEND_URL
        value: "http://fastapi-backend:8000"
    healthCheckPath: "/health"
    dockerfilePath: "EHR/app/frontend/Dockerfile"
